import { Question, Tag, User } from './types';

export const currentUser: User = {
  id: 'user1',
  name: 'Alex Student',
  role: 'student',
  avatar: '👨‍🎓',
};


export const users: User[] = [
  {
    id: 'user1',
    name: 'Alex Student',
    role: 'student',
    avatar: '👨‍🎓',
  },
  {
    id: 'user2',
    name: 'Dr. Emma Wilson',
    role: 'specialist',
    avatar: '👩‍⚕️',
    profession: 'Psychologist',
    expertise: ['Anxiety', 'Mental Health', 'Productivity'],
    verified: true,
  },
  {
    id: 'user3',
    name: 'Mark Johnson',
    role: 'specialist',
    avatar: '👨‍💼',
    profession: 'Corporate Strategist',
    expertise: ['Leadership', 'Startup Growth', 'Team Management'],
    verified: true,
  },
  {
  id: 'user4',
  name: 'Sarah Lee',
  role: 'student',
  avatar: '👩‍🎓',
  },

  {
    id: 'user5',
    name: 'Dr. Robert Kim',
    role: 'specialist',
    avatar: '👨‍⚕️',
    profession: 'Career Advisor',
    expertise: ['Interviews', 'Resume', 'Leadership'],
    verified: true,
  },

];


export const tags: Tag[] = [
  { name: 'mental-health', category: 'psychology' },
  { name: 'stress-management', category: 'psychology' },
  { name: 'motivation', category: 'psychology' },
  { name: 'counselling', category: 'psychology' },
  { name: 'interview', category: 'corporate' },
  { name: 'resume', category: 'corporate' },
  { name: 'leadership', category: 'corporate' },
  { name: 'teamwork', category: 'corporate' },
  { name: 'productivity', category: 'corporate' },
  { name: 'software', category: 'industry' },
  { name: 'ai-ml', category: 'industry' },
  { name: 'internship', category: 'industry' },
  { name: 'startup', category: 'industry' },
  { name: 'project-help', category: 'industry' },
];

export const questions: Question[] = [
  {
    id: 'q1',
    userId: 'user1',
    title: 'How to manage stress during final exams?',
    description: 'I am finding it really difficult to manage my stress levels during my final exams. I often feel overwhelmed and anxious. What are some effective strategies to cope with exam stress?',
    tags: ['stress-management', 'mental-health'],
    answers: [
      {
        id: 'a1',
        userId: 'user2',
        content: 'Start by creating a realistic study schedule that includes regular breaks. The Pomodoro Technique (25 minutes of focused study followed by 5-minute breaks) can be very effective. Also, make sure you\'re getting enough sleep, eating well, and exercising regularly. These physical factors significantly impact your mental resilience.',
        upvotes: 15,
        createdAt: '2024-01-15T10:30:00Z',
        isBest: true,
      },
      {
        id: 'a2',
        userId: 'user5',
        content: 'Practice mindfulness and deep breathing exercises. When you feel overwhelmed, take 5 minutes to do some breathing exercises. This can help reset your nervous system and improve focus.',
        upvotes: 8,
        createdAt: '2024-01-15T14:20:00Z',
        isBest: false,
      },
    ],
    views: 234,
    createdAt: '2024-01-15T09:00:00Z',
    status: 'answered',
  },
  {
    id: 'q2',
    userId: 'user4',
    title: 'Tips for preparing a strong resume for tech internships?',
    description: 'I am a sophomore looking for summer internships in software development. What should I include in my resume to make it stand out? I have done a few projects but no prior internship experience.',
    tags: ['resume', 'internship', 'software'],
    answers: [
      {
        id: 'a3',
        userId: 'user3',
        content: 'Focus on your projects! Include 3-4 strong projects with clear descriptions of what you built, the technologies you used, and the impact. Quantify whenever possible (e.g., "Built a web app that reduced processing time by 40%"). Also, make sure to include relevant coursework, technical skills, and any leadership positions in student organizations.',
        upvotes: 22,
        createdAt: '2024-01-16T11:00:00Z',
        isBest: true,
      },
    ],
    views: 189,
    createdAt: '2024-01-16T08:30:00Z',
    status: 'answered',
  },
  {
    id: 'q3',
    userId: 'user1',
    title: 'How to stay motivated when working on long-term projects?',
    description: 'I often start projects with great enthusiasm but lose motivation halfway through. How can I maintain consistent motivation for long-term goals?',
    tags: ['motivation', 'productivity'],
    answers: [],
    views: 67,
    createdAt: '2024-01-17T14:00:00Z',
    status: 'pending',
  },
  {
    id: 'q4',
    userId: 'user4',
    title: 'What are the key skills needed for a leadership role?',
    description: 'I recently got an opportunity to lead a team project at my university. I have never been in a leadership position before. What are the essential skills I should develop to be an effective leader?',
    tags: ['leadership', 'teamwork'],
    answers: [
      {
        id: 'a4',
        userId: 'user3',
        content: 'Communication is the foundation of good leadership. You need to be able to clearly articulate goals, expectations, and feedback. Also, develop active listening skills - understand your team members\' perspectives and concerns. Delegation is equally important; trust your team and assign tasks based on individual strengths.',
        upvotes: 18,
        createdAt: '2024-01-18T09:45:00Z',
        isBest: false,
      },
      {
        id: 'a5',
        userId: 'user5',
        content: 'Be empathetic and lead by example. Show up on time, meet deadlines, and maintain a positive attitude. Your team will mirror your behavior. Also, don\'t be afraid to admit when you don\'t know something - it builds trust and encourages open communication.',
        upvotes: 14,
        createdAt: '2024-01-18T11:20:00Z',
        isBest: true,
      },
    ],
    views: 156,
    createdAt: '2024-01-18T08:00:00Z',
    status: 'answered',
  },
  {
    id: 'q5',
    userId: 'user4',
    title: 'Best practices for technical interviews in AI/ML roles?',
    description: 'I have an upcoming interview for an AI/ML internship position. What kind of questions should I expect, and how should I prepare?',
    tags: ['interview', 'ai-ml'],
    answers: [
      {
        id: 'a6',
        userId: 'user3',
        content: 'Expect a mix of theoretical questions (machine learning algorithms, statistics, linear algebra) and practical coding challenges. Review fundamental ML algorithms like linear regression, decision trees, and neural networks. Be prepared to explain your project work in detail and discuss the trade-offs of different approaches.',
        upvotes: 25,
        createdAt: '2024-01-19T10:15:00Z',
        isBest: true,
      },
    ],
    views: 201,
    createdAt: '2024-01-19T07:30:00Z',
    status: 'answered',
  },
  {
    id: 'q6',
    userId: 'user1',
    title: 'How to deal with imposter syndrome in academic settings?',
    description: 'I constantly feel like I don\'t belong in my program, even though I have good grades. How do I overcome these feelings of inadequacy?',
    tags: ['mental-health', 'motivation'],
    answers: [],
    views: 92,
    createdAt: '2024-01-20T12:00:00Z',
    status: 'pending',
  },
  {
    id: 'q7',
    userId: 'user4',
    title: 'Advice for joining a startup vs. established company?',
    description: 'I have offers from both a startup and a well-established tech company for my summer internship. What factors should I consider when making this decision?',
    tags: ['startup', 'internship'],
    answers: [
      {
        id: 'a7',
        userId: 'user3',
        content: 'Both have pros and cons. Startups offer more hands-on experience, diverse responsibilities, and direct impact, but can be less structured with fewer resources. Established companies provide better mentorship, structured programs, and brand recognition, but your role might be more narrowly defined. Consider what you want to learn and which environment matches your working style.',
        upvotes: 19,
        createdAt: '2024-01-21T09:30:00Z',
        isBest: true,
      },
    ],
    views: 178,
    createdAt: '2024-01-21T08:00:00Z',
    status: 'answered',
  },
  {
    id: 'q8',
    userId: 'user1',
    title: 'How to effectively communicate with team members in remote settings?',
    description: 'My team is working remotely on a group project, and we are facing communication challenges. How can we improve our remote collaboration?',
    tags: ['teamwork', 'productivity'],
    answers: [],
    views: 45,
    createdAt: '2024-01-22T10:00:00Z',
    status: 'pending',
  },
];
